apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.backend.appname}}
  name: {{.Values.backend.svcname}}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: {{.Values.backend.appname}}
  type: ClusterIP
status:
  loadBalancer: {}
