apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.proxy.appname}}
  name: {{.Values.proxy.svcname}}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30081
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30444
  selector:
    app: {{.Values.proxy.appname}}
  type: NodePort
status:
  loadBalancer: {}
