apiVersion: v1
kind: Service
metadata:
  labels:
    app: proxy-deployment
  name: proxy-deployment
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443
  selector:
    app: proxy-deployment
  type: NodePort
status:
  loadBalancer: {}
